version: '3'
services:
  citizen:
    build:
        context: .
        dockerfile: ./Dockerfile
    environment:
        FLASK_APP: /app/src/app.py
    # command: python3 /app/src/app.py
    command: "flask run --host 0.0.0.0 --port 5000"
    tty: true 
    volumes:
      - ./src:/app/src
    ports:
      - 8092:5000
    networks:
        - makuhari_city
networks:
  makuhari_city:
    external: true