version: "3"
services: 
  goapp: 
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command: go run main.go
    tty: true 
    volumes:
      - ./ipfs_api:/go/src/app
    ports:
      - "8091:8080"
    networks:
        - makuhari_city

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    command: ["daemon", "--enable-pubsub-experiment"]
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8090:8080" # ipfs gateway
    volumes:
      - ./ipfs:/data/ipfs
    networks:
        - makuhari_city

networks:
  makuhari_city:
    external: true
