version: "3"
services: 
  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./proxy/public:/var/www/html
        - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ../../ssl/cert:/etc/nginx/ssl
    networks:
        - makuhari_city
    extra_hosts:
        - "host.docker.internal:host-gateway"

  ipfs-api: 
    build:
      context: .
      dockerfile: ./ipfs/Dockerfile
    command: go run main.go
    tty: true 
    volumes:
      - ./ipfs/api:/go/src/app
    ports:
      - "8091:8080"
    networks:
        - makuhari_city

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    command: ["daemon", "--enable-pubsub-experiment"]
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8090:8080" # ipfs gateway
    volumes:
      - ./ipfs/data:/data/ipfs
    networks:
        - makuhari_city

networks:
  makuhari_city:
    external: true
