version: "3"
services: 
  goapp: 
    build:
      context: .
      dockerfile: ./build/Dockerfile
    tty: true 
    volumes:
      - ./cmd:/go/src/app

  dump:
    build:
      context: .
      dockerfile: ./dump/Dockerfile
    ports:
      - "8082:8082"
