version: "3"
services: 
  goapp: 
    build:
      context: .
      dockerfile: ./build/Dockerfile
    tty: true 
    volumes:
      - ./cmd:/go/src/app
    ports:
      - "8091:8080"
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    command: ["daemon", "--enable-pubsub-experiment"]
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8090:8080" # ipfs gateway
    volumes:
      - ./data/ipfs:/data/ipfs

