version: '3'
services:
  nginx:
    build: .
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./public:/var/www/html
        - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ../../ssl/cert:/etc/nginx/ssl
    networks:
        - makuhari_city
    extra_hosts:
        - "host.docker.internal:host-gateway"

networks:
  makuhari_city:
    external: true
